### ISSUE TITLE
Cannot save report: AttributeError: 'QgsProject' object has no attribute 'lastSaveDateTime'

### ISSUE THREAD

**Issue by ygarb** [sigdeletras/project-reports-qgis-plugin#7]
**Describe the bug**
On trying to save a project report (all options ticked and the output directory path defined) I get the following notification:

Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\project_report\project_report_dockwidget.py", line 189, in set_folder
    self.project = QProjectReport(self.qgs_project, self.folder_path)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\project_report\QProjectReport.py", line 182, in __init__
    self.qgsproject.lastSaveDateTime().date().toString("yyyy-MM-dd")
AttributeError: 'QgsProject' object has no attribute 'lastSaveDateTime'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Running  QGIS version 3.6.2-Noosa on a solid modern machine (i7, enough memory) under Windows 10.

**Comment by ygarb** [comment]
When I run the same request with "relations" and "joins" not checked, the report is not created.  I get the following python warning

2023-07-11T20:16:26     WARNING    Traceback (most recent call last):
              File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\project_report\project_report_dockwidget.py", line 108, in check_folder
              if os.path.exists(self.project.report_directory):
             AttributeError: 'ProjectReportDockWidget' object has no attribute 'project'
